### PR TITLE
Optimise pinging

### LINKED ISSUE #191: Add debounce for pings
Currently we blindly reply to all broadcast messages coming from storage with a ping.
We need to debounce those replies to limit the number of pings we send consecutively to the same contact.

### LINKED ISSUE #192: P2P does not recover after 1 failed message
Currently we set a contact as offline as soon as we fail to send him 1 message via P2P.
Once marked as offline, we have no way to restore the P2P session unless one of the two participants restart their application, which would send a broadcast message.

When we are online, we currently only send a broadcast message (or ping) to our online contacts. Maybe we should attempt sending a ping to all contacts for which we have a .loki address stored in memory.

### PR DESCRIPTION
**Pull request by BeaudanBrown**
Refactored the pinging logic to handle a couple edge cases better
Ttl for online broadcast messages is now only 1 min
More sensible variable names for ping related things
Now ping our contacts that go offline every 2 mins to check if they are back online
Ping our contacts if they sent us a storage server message in the last 2 mins

Along the way I stumbled across a couple bugs in the snode logic that would cause the nodes to always be removed on the first error rather than trying 3 times, and changed the logging to print a warning for the first 2 failures of a snode and then an error when it is removed from memory

Although I didn't end up actually doing a debounce for the pings (because it would have made the system less reliable), this resolves #191 
Also fixes #192 

Tried a bunch and considered heaps of different stuff during this PR, still not happy with the pinging but I think the nature of the architecture means we are just going to have to accept that the online indicator won't always be very accurate

### CODE REVIEW

File: js/modules/loki_p2p_api.js [hunk 1]
```diff
@@ -16,43 +18,80 @@ class LokiP2pAPI extends EventEmitter {
...
   getContactP2pDetails(pubKey) {
     return this.contactP2pDetails[pubKey] || null;
   }
 
+  isContactOnline(pubKey) {
+    const contactDetails = this.contactP2pDetails[pubKey];
+    if (!contactDetails || !contactDetails.isOnline) {
+      return false;
+    }
+    return contactDetails.isOnline;
```
Comment (Mikunj) [inline js/modules/loki_p2p_api.js]:
```suggestion
    return !!(contactDetails && contactDetails.isOnline);
```
this function can be shortened to that

Comment (BeaudanBrown) [reply js/modules/loki_p2p_api.js]: Mmm I don't really like `!!`, it scares and confuses me

Comment (Mikunj) [reply js/modules/loki_p2p_api.js]: it just converts any value to `boolean`

Comment (sachaaaaa) [reply js/modules/loki_p2p_api.js]: I agree with Mikunj, we should find a place in our hearts to welcome `!!` in our lives.

Comment (BeaudanBrown) [reply js/modules/loki_p2p_api.js]: Ya I mean I get how it works I just think it takes more of my brain power to parse what that one liner is doing when I go back to read the code but maybe will become more natural with repeated use :+1:
