### PR TITLE
Fix contact display

### LINKED ISSUE #134: Conversations aren't added to the "Contacts" section until you send/receive a message from friend
### Bug description

When you are adding a new contact they don't show up in your contacts list until a message has been sent or received after they have been added as friends.

### Steps to reproduce

1.  Send a friend request from A to B
2.  Have B accept the friend request

Actual result:

The conversation for A and B is only shown in the "Conversations" tab but not the "Contacts" tab until another message is shared between them.

Expected result:

The conversation should appear in the "Contacts" tab for B as soon as they have sent the accept friend request message and for A as soon as they receive the friend request accepted message.

### PR DESCRIPTION
**Pull request by Mikunj**
Fixes #134 

This also fixes a minor notification bug that i missed.

### CODE REVIEW

File: js/notifications.js [hunk 1]
```diff
@@ -100,8 +100,15 @@
...
-          title = 'Signal';
-          message = newMessageCountLabel;
+          title = 'Loki Messenger';
+
+          if (last.isFriendRequest) {
+            message = `Friend request ${last.friendRequestType}`;
+          } else if (messagesNotificationCount > 0) {
+            message = newMessageCountLabel;
+          } else {
+            message = '-';
```
Comment (sachaaaaa) [inline js/notifications.js]: As discussed offline, we should simply handle this "should never happen" case by returning early?

Comment (sachaaaaa) [reply js/notifications.js]: I guess so :)
