### PR TITLE
Public chat duplicate message fix

### LINKED ISSUE #504: Duplicate messages aren't being filtered out
**Describe the bug**
If the same message was replayed to the chat server, the desktop client doesn't filter it out causing it to display the same message however many times it was replayed.

**To Reproduce**
1. Send the same message (as in instead of doing 1 api call, run the same call twice)
2. View the chat on desktop. It should show 2 of the same message.

### PR DESCRIPTION
**Pull request by Mikunj**
This PR makes it so any similar messages fetched through the public chat will be ignored if:
The same author posted the message, The message has the same text AND the message was sent within 10 seconds.

This will alleviate the display of spam somewhat but is not the perfect counter measure as someone could spam the same message every 10 seconds.

Fixes #504

### CODE REVIEW

File: js/modules/loki_public_chat_api.js [hunk 1]
```diff
@@ -574,6 +578,33 @@ class LokiPublicChannelAPI {
...
         }
 
+        // Duplicate check
+        const isDuplicate = message => {
+          // The username in this case is the users pubKey
+          const sameUsername = message.username === adnMessage.user.username;
+          const sameText = message.text === adnMessage.text;
+          // Don't filter out messages that are too far apart from each other
+          const timestampsSimilar =
+            Math.abs(message.timestamp - timestamp) <= 10000;
```
Comment (sachaaaaa) [inline js/modules/loki_public_chat_api.js]: I would just upgrade the `10000` to its own const variable, e.g. at the top of the file.
