### PR TITLE
Fix friend request timer bug

### LINKED ISSUE #200: Friend request timer resets after accepted
### Bug Description

We set a friend request timeout timer to allow people to resend friend requests if they might have been cleared from the storage server, but it also triggers after the friend request exchange has been completed

### Steps to Reproduce

1.  Perform friend request exchange
2.  Wait 4 days

Actual Result:

Friend request status on the initial friend request sender gets reset to none

Expected Result:

Both parties should remain friends

### PR DESCRIPTION
**Pull request by BeaudanBrown**
Clear timers after friend request complete and don't do timer related things if we are already friends

Fixes #200

### CODE REVIEW

File: js/models/conversations.js [hunk 1]
```diff
@@ -663,6 +665,7 @@
     async onFriendRequestTimeout() {
       // Unset the timer
       if (this.unlockTimer) clearTimeout(this.unlockTimer);
+      if (this.isFriend) return;
```
Comment (Mikunj) [inline js/models/conversations.js]:
```suggestion
      if (this.isFriend()) return;
```

This should be placed after
```js
this.unlockTimer = null;
```

File: js/models/conversations.js [hunk 2]
```diff
@@ -715,6 +718,7 @@
       await this.setFriendRequestStatus(FriendRequestStatusEnum.requestSent);
     },
     setFriendRequestExpiryTimeout() {
+      if (this.isFriend) return;
```
Comment (Mikunj) [inline js/models/conversations.js]:
```suggestion
      if (this.isFriend()) return;
```

File: js/models/conversations.js (hunk 1 above)
Comment (BeaudanBrown) [reply js/models/conversations.js]: Lol I'm dum
